apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: { app: {{ include "app-chart.name" . }} }
  ports: [ { name: http, port: {{ .Values.service.port }}, targetPort: http, protocol: TCP } ]
